name: Release and deploy GoLang

on:
  push:
    branches:
    - "v<digit>.<digit>"

jobs:
  release-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Echo the branch name
      run: echo "current branch - ${{ github.ref_name }}"
    - name: Checkout the branch
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref_name }}